apiVersion: v1
kind: Service
metadata:
  labels:
    app: runner-ubuntu
  name: runner-ubuntu
  namespace: development
spec:
  ports:
    - port: 8000
  selector:
    app: runner-ubuntu
  type: ClusterIP